version: '3.8'

services:
  crawler:
    build: .
    container_name: mombabymarket-crawler
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - CRAWL_BATCH_SIZE=5
      - CRAWL_DELAY=2000
      - MAX_RETRIES=3
      - HEADLESS=true
      - LOG_LEVEL=info
    networks:
      - crawler-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: MongoDB for storing results
  mongodb:
    image: mongo:6.0
    container_name: crawler-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    networks:
      - crawler-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  crawler-network:
    driver: bridge
